### ISSUE TITLE
Can't merge layers, no snapping rectangle for pixel art, and doubling image resolution from PDFs.

### ISSUE THREAD

**Issue by Mario662629** [photopea/vectorpea#85]
There is no right-click context menu on the layers that allows you to merge them. In addition, there is no "snapping rectangle tool" that could be used for vectorizing pixel art.

In addition, when saving a PDF as an SVG, it is exported at double resolution compared to what was entered (e.g. 36x36 turns into 72x72). You can see this by saving a PDF page as an SVG, then opening the exported copy in Vectorpea and preparing to export that. Look at the resolution values.

**Comment by Mario662629** [comment]
In addition, the file changes a tiny bit when converting, as seen when exporting the original PDF as a PNG in Vectorpea, compared to one that is exported as SVG and then to PNG. Both same resolution. Try using the eyedropper in Photopea to look for pixels that are not #000000.

<img width="3532" alt="Image" src="https://github.com/user-attachments/assets/4d950aa2-33dc-4fae-bab0-f67ce81e9d55" />

**Comment by photopea** [comment]
Merging layers: What exactly do you want to do to that SVG? There are four shapes, one covering another. Can any software do what you want to do? Which software? It makes no sense to me what you describe. Also, there are no white objects, just black and yellow.

Vectorizing Pixel Art: I have added the "Vectorize Bitmap" button to the top menu (appears when you select a bitmap layer)

PDF to SVG Resolution: I am a bit confused, what should I do to see this problem?

**Comment by photopea** [comment]
I have fixed the issue with a size of the imported PDF (and exporting it as an SVG).

I have fixed the issue with a message about buying Premium.

Merging layers in Photopea: I think Photopea does exactly what Photoshop would do. You should set a boolean operation to each path of the shape. It is described e.g. here: https://www.photopea.com/learn/vg-structure

Merging layers in Vectorpea: I think you can not merge the black arrow, that is fully inside a black square, with that square, and expect the yellow color to appear between the arrow and the square. If you can do it in some software, please, show us what you get, so that I can get a clue of what you want to achieve.

**Comment by photopea** [comment]
"Still can't merge the black border because it's under the yellow part" - as I said, I dont think it can be done automatically, by a computer. If you think some program / computer can do it, tell me which one (as a proof that it is possible).

PDF White / transparent background - how do you tell if a PDF file has a white or a transparent background? What software do you use for that?

**Comment by photopea** [comment]
What is "add right-click context menu on layers"? Do you mean on layers in the canvas, or on layers in the Layers panel? We want Vectorpea to work the same as Adobe Illustrator, and there is no right-click context menu in Illustrator.

**Comment by photopea** [comment]
We want Vectorpea to work as Illustrator, not as Photopea, and there is no such menu in Illustrator.

**Comment by Mario662629** [comment]
Here are the other issues:
- Add right-click context menu on layers in Vectorpea for merging layers and clipping masks, at least. The "still can't merge the black border" will be managed later.
- Fix scrolling and zooming bugs when using "Fit to Artwork Bounds" on content outside a PDF's canvas.
- Fix inability to change colors of multiple selected layers of different colors.
- Fix vectorize bitmap issue for pixel art on Photopea and Vectorpea.
- Fix softlock when dragging a folder onto Photopea or Vectorpea.

**Comment by photopea** [comment]
- I have fixed the zooming / scrolling when the artboard is moved far from the original location
- You can change colors of multiple shapes with different colors at once
- "softlock" - I guess you mean drag-and-dropping a folder from your computer into an opened document. Now, Photopea should tell you that you can not open folders.

If both the width and the height of the image is 32 pixels or less, it is considered to be a "pixel art". When you vectorize pixel art, now, it should only trace around pixels, without trying to create any curves.

To combine multiple shapes together, in Vectorpea or in Adobe Illustrator, you should use the Pathfinder tool. See https://helpx.adobe.com/illustrator/using/combining-objects.html

**Comment by Mario662629** [comment]
There are object sprites that are larger than 32 pixels in either direction from the Mario franchise that can still create curves at the original resolution. Examples include:
## In-game pixel logos from retro games
The logos on the title screens in retro games.
- Super Mario Bros. (176x88): https://www.mariowiki.com/File:SMB_In-game_Logo.png

## Sprites of large objects
Sprites of objects that are longer than 2 tiles in width and/or height. 1 tile is 16x16 pixels.
### Super Mario Bros.
- Fortress (80x80): https://www.mariowiki.com/File:SMB_Fortress.png
### Super Mario World
- Bowser (64x96): https://www.mariowiki.com/File:SMW-Bowser_in_Koopa_Clown_Car.gif
### Super Mario Maker
- Grinder (SMB style) (48x48): https://www.mariowiki.com/File:SMM-SMB-Grinder.png
- Skewer (SMB style) (64x64): https://www.mariowiki.com/File:SMM-SMB-Skewer.png

## Sprites of long or tall objects
Sprites of objects that can be variable in length that are longer than 2 tiles in height (vertical) or length (horizontal)
### Super Mario Bros.
- Goal Pole at full length (24x168): https://www.mariowiki.com/File:SMB_Goal_Pole.png
- Warp Pipes longer than 2 tiles in height, including those that are multi-way: https://www.mariowiki.com/File:SMBWarpPipeForked.png
### Super Mario Bros. 2
- Vases longer than 2 tiles in height: https://www.mariowiki.com/File:Vase_SMB2_Sprite.png

**Comment by Mario662629** [comment]
To make pixel art scalable.

**Comment by Mario662629** [comment]
It means making sprites from retro video games scalable without being blurry. This currently can be done with PNG files in Photopea to upscale them, but you'll have to create versions for many different resolutions or apply a large multiplier to the scaling. It also can be accomplished by "redrawing" the sprite using the Rectangle Tool.

## Demonstration
### Original sprite, 10x sixe:
<img width="120" height="160" alt="Image" src="https://github.com/user-attachments/assets/9043cf04-ed73-4da8-a697-35571c52dc01" />

### Upscaled sprite, same size:
<img width="120" height="160" alt="Image" src="https://github.com/user-attachments/assets/5f58bb8e-f277-4124-8f88-2e9ce5fa27ff" />

### Original sprite put in Vectorize Bitmap:
<img width="1132" height="1118" alt="Image" src="https://github.com/user-attachments/assets/a430b957-e778-43c5-8df3-99bb6b0aa3be" />

---

In addition, I noticed the inability to split layers in Vectorpea, like when a layer consists of multiple shapes. Things tried:
- Copying a layer (or parts of it) using Ctrl+C, and pasting it onto a new one using Ctrl+V doesn't work.
- There is no "Release to Layers" option to split the layers.
- There is no option to copy layers.

**Comment by photopea** [comment]
Your "blurry mario" is caused by using a bilinear interpolation when upscaling. You just need to set a different upscaling method, e.g. "nearest neighbour". Every software which upscales raster images should allow you to choose the upscaling method.

To prevent same colors from merging into one layer during "Vectorize", you should turn off "Merge colors" at the top.

Could you clear your cache in Photopea? I think then, these ads should not appear anymore.

**Comment by photopea** [comment]
As I said, Vectorize is for vectorizing raster graphics into vector graphics (converting pixels to curves). It will not convert every pixel to a vector square. I tihnk such a feature is useless, nobody ever asked us about such a feature.

To "Merge" and "Unmerge" paths in Adobe Illustrator, you should use Object - Compound Path - Make / Release. I have added this feature to Photopea.

You can duplicate layers by pressing Ctrl+C and Ctrl+V, or Edit - Copy, Edit - Paste. Unless you use Firefox, which is really a bad web browser and nothing works in it properly.
